- import_playbook: distribution.yml

- name: deploy for all hosts
  hosts: '{{ hosts_name }}'
  gather_facts: false
  tasks:
    - name: gather facts
      setup:
        fact_path: /notexist
    
    - name: set resources_dir local
      set_fact:
        resources_dir: "{{ inventory_dir }}/resources"
        cacheable: yes
      when: ansible_connection == "local"

    - name: set resources_dir remote
      set_fact:
        resources_dir: "{{ ansible_user_dir }}/resources"
        cacheable: yes
      when: ansible_connection != "local"
    
    - import_tasks: install.yml
    
    - name: check model
      stat:
        path: /run/board_cfg.ini
      register: a500
      when: server is undefined
    
    - name: set kmsagent path
      set_fact:
        kmsagent_path: "{{ '/usr/local/Ascend/driver/tools/kmsagent' if not a500.stat.exists else '/home/data/miniD/driver/tools/kmsagent' }}"
        cacheable: yes
      when: server is undefined
    
    - name: Check whether the cert directory exists
      stat:
        path: /opt/cert
      register: dir_result
      when:
        - server is undefined
        - ansible_connection != "local" or (ansible_connection == "local" and remoteonly == "n")

    - name: clean resources
      file:
        state: absent
        path: /opt/cert
      when:
        - server is undefined and dir_result.stat|d("") != "" and dir_result.stat.exists
        - ansible_connection != "local" or (ansible_connection == "local" and remoteonly == "n")
    
    - name: copy ca files
      shell: cp -r {{ resources_dir }}/cert /opt
      when:
        - server is undefined
        - ansible_connection != "local" or (ansible_connection == "local" and remoteonly == "n")
    
    - name: set cert dir permission
      file:
        path: /opt/cert
        owner: HwHiAiUser
        group: HwHiAiUser
        mode: 0700
        recurse: no
      when:
        - server is undefined
        - ansible_connection != "local" or (ansible_connection == "local" and remoteonly == "n")
    
    - name: set cafile permission first
      file:
        path: /opt/cert/ca.key
        owner: HwHiAiUser
        group: HwHiAiUser
        mode: 0600
      when:
        - server is undefined
        - ansible_connection != "local" or (ansible_connection == "local" and remoteonly == "n")
    
    - name: set cafile permission second
      file:
        path: /opt/cert/ca.pem
        owner: HwHiAiUser
        group: HwHiAiUser
        mode: 0600
      when:
        - server is undefined
        - ansible_connection != "local" or (ansible_connection == "local" and remoteonly == "n")

    - name: Check whether the docker network aiguard exists
      shell: docker network ls | grep aiguard | wc -l
      register: aiguard_result
      when:
        - server is undefined
        - ansible_connection != "local" or (ansible_connection == "local" and remoteonly == "n")
    
    - name: docker create network aiguard
      shell: docker network create aiguard
      when:
        - server is undefined and aiguard_result.stdout|d("") != "" and aiguard_result.stdout == "0"
        - ansible_connection != "local" or (ansible_connection == "local" and remoteonly == "n")
    
    - name: get CfsIP
      shell: docker network inspect aiguard | grep Gateway|cut -d'"' -f4
      register: cfsip
      when:
        - server is undefined
        - ansible_connection != "local" or (ansible_connection == "local" and remoteonly == "n")
    
    - name: Configuring the cfs service
      shell: |
        {{ kmsagent_path }} -c /var/kmsagentd/kmsagent.conf -k /var/kmsagentd/kmsconf.ksf -s SERVER -n CfsIP -v {{ cfsip.stdout }}
        {{ kmsagent_path }} -c /var/kmsagentd/kmsagent.conf -k /var/kmsagentd/kmsconf.ksf -s SERVER -n CfsPort -v {{ cfs_port }}
      environment:
        LD_LIBRARY_PATH: "/usr/local/Ascend/driver/lib64/inner/:/usr/local/Ascend/develop/lib64/"
      when:
        - server is undefined
        - ansible_connection != "local" or (ansible_connection == "local" and remoteonly == "n")
    
    - name: Configuring the aivault service
      shell: |
        {{ kmsagent_path }} -c /var/kmsagentd/kmsagent.conf -k /var/kmsagentd/kmsconf.ksf -s AIVAULT_SERVER -n AiVaultIP -v {{ aivault_ip }}
        {{ kmsagent_path }} -c /var/kmsagentd/kmsagent.conf -k /var/kmsagentd/kmsconf.ksf -s AIVAULT_SERVER -n AiVaultPort -v {{ aivault_port }}
        {{ kmsagent_path }} -c /var/kmsagentd/kmsagent.conf -k /var/kmsagentd/kmsconf.ksf -s AIVAULT_SERVER -n AiVaultCaPath -v /opt/cert/ca.pem
      environment:
        LD_LIBRARY_PATH: "/usr/local/Ascend/driver/lib64/inner/:/usr/local/Ascend/develop/lib64/"
      when:
        - server is undefined
        - ansible_connection != "local" or (ansible_connection == "local" and remoteonly == "n")
    
    - name: Check whether the TlsCertPath directory exists
      stat:
        path: /opt/tlscert
      register: tlscert_result
      when:
        - server is undefined
        - ansible_connection != "local" or (ansible_connection == "local" and remoteonly == "n")
    
    - name: create TlsCertPath
      shell: mkdir /opt/tlscert
      when:
        - server is undefined and tlscert_result.stat|d("") != "" and not tlscert_result.stat.exists
        - ansible_connection != "local" or (ansible_connection == "local" and remoteonly == "n")
    
    - name: Check whether the TlsBackupCertPath directory exists
      stat:
        path: /opt/tlscertbak
      register: tlscertbak_result
      when:
        - server is undefined
        - ansible_connection != "local" or (ansible_connection == "local" and remoteonly == "n")
    
    - name: create TlsBackupCertPath
      shell: mkdir /opt/tlscertbak
      when:
        - server is undefined and tlscertbak_result.stat|d("") != "" and not tlscertbak_result.stat.exists
        - ansible_connection != "local" or (ansible_connection == "local" and remoteonly == "n")
    
    - name: Start kmsagent service
      shell: npu-smi set -t key-manage -s start
      when:
        - server is undefined
        - ansible_connection != "local" or (ansible_connection == "local" and remoteonly == "n")
    
    - name: Generate kmsagent.csr
      shell: |
        {{ kmsagent_path }} tls get-csr "rsa:4096:sha256" "KMSAgent|chengdu|sichuan|Ascend|CN" /var/kmsagentd/kmsagent.conf /var/kmsagentd/kmsconf.ksf
      environment:
        LD_LIBRARY_PATH: "/usr/local/Ascend/driver/lib64/inner/:/usr/local/Ascend/develop/lib64/"
      when:
        - server is undefined
        - ansible_connection != "local" or (ansible_connection == "local" and remoteonly == "n")
    
    - name: Copy kmsagent.csr from remote host to local
      fetch:
        src: /opt/tlscert/tmp/kmsagent.csr
        dest: "{{ hostvars.localhost.resources_dir }}"
      when: server is undefined and ansible_connection != "local"
    
    - name: Generate kmsagent.pem
      shell: python3 {{ resources_dir }}/../certs.py {{ remoteonly }}
      when: server is undefined and ansible_connection == "local"
    
    - name: copy kmsagent.pem to remote hosts
      copy:
        src: "{{ hostvars.localhost.resources_dir }}/{{ hostvars[inventory_hostname]['inventory_hostname'] }}/opt/tlscert/tmp/kmsagent.pem"
        dest: /opt/tlscert/tmp
      when: server is undefined and ansible_connection != "local"

    
    - name: Import kmsagent certificate
      shell: |
        {{ kmsagent_path }} tls set-cert "/opt/tlscert/tmp/kmsagent.pem /opt/cert/ca.pem" /var/kmsagentd/kmsagent.conf /var/kmsagentd/kmsconf.ksf
      environment:
        LD_LIBRARY_PATH: "/usr/local/Ascend/driver/lib64/inner/:/usr/local/Ascend/develop/lib64/"
      when:
        - server is undefined
        - ansible_connection != "local" or (ansible_connection == "local" and remoteonly == "n")

    - name: set TlsCertPath directory permission
      file:
        path: /opt/tlscert
        owner: HwHiAiUser
        group: HwHiAiUser
        recurse: yes
      when:
        - server is undefined
        - ansible_connection != "local" or (ansible_connection == "local" and remoteonly == "n")
    
    - name: set TlsBackupCertPath directory permission
      file:
        path: /opt/tlscertbak
        owner: HwHiAiUser
        group: HwHiAiUser
        recurse: yes
      when:
        - server is undefined
        - ansible_connection != "local" or (ansible_connection == "local" and remoteonly == "n")
    
    - name: restart the kmsagent service
      shell: |
        npu-smi set -t key-manage -s stop
        npu-smi set -t key-manage -s start
      when:
        - server is undefined
        - ansible_connection != "local" or (ansible_connection == "local" and remoteonly == "n")
    
    - name: Check the running state of kmsagent
      shell: npu-smi info -t key-manage
      register: kmsagent_stat
      when:
        - server is undefined
        - ansible_connection != "local" or (ansible_connection == "local" and remoteonly == "n")
    
    - name: message
      debug:
        msg:
          - "{{ kmsagent_stat | default('NOT DEFINED') }}"
      when:
        - server is undefined and kmsagent_stat.changed
        - ansible_connection != "local" or (ansible_connection == "local" and remoteonly == "n")